<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.neko</groupId>
        <artifactId>user-task-reminder</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>user-task-reminder-web</artifactId>
    <packaging>jar</packaging>
    <name>user-task-reminder-web</name>
    <description>REST API, schedulers and application bootstrap</description>

    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
        </dependency>

        <!-- Reactor modules -->
        <dependency>
            <groupId>com.neko</groupId>
            <artifactId>user-task-reminder-model</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.neko</groupId>
            <artifactId>user-task-reminder-db</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.neko</groupId>
            <artifactId>user-task-reminder-service</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>user-task-reminder</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
